project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from app.views import *





urlpatterns = [
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^first_view/(?P<starts_with>\w+)/$', 'app.views.first_view'),
    url(r'^get_post', 'app.views.get_post'),
    url(r'^template_view', 'app.views.template_view'),
    url(r'^state_list_view/', StateListView.as_view()),
    url(r'states/(?P<pk>[0-9]+)/$', 'app.views.state_detail'),
    url(r'cities/(?P<pk>[0-9]+)/$', CityDetailView.as_view()),
    url(r'city_search/$', 'app.views.city_search'),
    url(r'^city_create/', 'app.views.city_create'),
    url(r'city_delete/$', 'app.views.city_delete'),
    url(r'user_signup/$', 'app.views.user_signup'),













]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models

# Create your models here.
import app


class State(models.Model):
    abbreviation = models.CharField(max_length=2)
    name = models.CharField(max_length=100, unique=True, null=True)



    def __unicode__(self):
        return self.name

class StateCapital(models.Model):
    name = models.CharField(max_length=100)
    state = models.OneToOneField("app.State")
    latitude = models.FloatField(null=True)
    longitude = models.FloatField(null=True)
    population = models.IntegerField(null=True)

    def __unicode__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True, unique=False)

    county = models.CharField(max_length=100, null=True)
    state = models.ForeignKey("app.State", null=True, blank=True)
    latitude = models.FloatField(null=True)
    longitude = models.FloatField(null=True)

    def __unicode__(self):
        return self.name

app/templates/base.html
<!DOCTYPE html>
  {% load static %}


<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>States</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static 'css/creative.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
  <body id="page-top">

      <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="/state_list_view/">US STATES</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="/city_search/">Search  <span class="glyphicon glyphicon-search"></span></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/city_delete/">Delete City  <span class="glyphicon glyphicon-user"></span></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/city_create/">Create New City  <span class="glyphicon glyphicon-user"></span></a>
                    </li>

                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    {% block body %}
    {% endblock %}



    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src=" {% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="{% static 'vendor/scrollreveal/scrollreveal.min.js' %}"></script>
    <script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'js/creative.min.js' %}"></script>



  </body>
</html>

app/templates/base2.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Creative - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="vendor/magnific-popup/magnific-popup.css" rel="stylesheet">

    <!-- Theme CSS -->
    <link  href="{% static " rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1 id="homeHeading">Your Favorite Source of Free Bootstrap Themes</h1>
                <hr>
                <p>Start Bootstrap can help you build better websites using the Bootstrap CSS framework! Just download your template and start going, no strings attached!</p>
                <a href="#about" class="btn btn-primary btn-xl page-scroll">Find Out More</a>
            </div>
        </div>
    </header>



</body>

app/templates/city_create.html
{% extends 'base.html' %}
{% block body %}

{% load crispy_forms_tags %}

{% load static %}


<header>

    <div class="header-content" >
        <div class="header-content-inner" style="padding:40px;">
            <h2 style="text-transform: uppercase;"> Add City here:  </h2>
            <br>



            <form method="POST" action="/city_create/">

            {{ form|crispy }}

            <input type="submit" value="Save" class="btn btn-primary" />

        </form>
            <br>
            <br>


                 {% if messages %}
             <div class="alert alert-success">

            {% for message in messages %}
                {{ message }}

            {% endfor %}


             </div>
                    {% endif %}



            </div>






        </div>



    </div>







</header>



</br>
</br>

<br>

{% endblock %}

app/templates/city_delete.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
{% load crispy_forms_tags %}



<header>

    <div class="header-content">
        <div class="header-content-inner" style="padding:40px;">
            <form action="/city_delete/" method="POST">

                 {% csrf_token %}
                    {{form|crispy}}
                    <input type="submit" value="Delete City" class="btn btn-primary">

            </form>
            <br>
            <br>
            {% if messages %}
                <div class="alert alert-success">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}

                </div>
            {% endif %}







        </div>




        </div>

    </div>



</header>





{% endblock %}

app/templates/city_detail.html
{% extends 'base.html' %}
{% block body %}
{% load static %}

<section class="bg-primary" style="margin:0%; background-image: url('{% static "img/header.jpg" %}'); background-size: 100%;">

    <div class="container">

        <h3> City Name :</h3>
        {{city.name}}
        <br>
        <br>


        <h4> City State:</h4>
        {{city.state}}
        <br>
        <br>




        <h4> City county:</h4>
        {{city.county}}
        <br>
        <br>


        <h4>Latitude & longitude</h4>
        {{city.latitude}} | {{city.longitude}}
        <br>
    </div>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>




</section>


{% endblock %}

app/templates/city_search.html
{% extends 'base.html' %}
{% block body %}
{% load static %}

{% load crispy_forms_tags %}


<header >
    <div class="header-content" >
            <div class="header-content-inner" >






                <form method="post" action = "/city_search/" >


                {% csrf_token %}

                {{ form|crispy }}

                <input class= "btn btn-primary" type="submit" value="Search Cities">
                    <br>
                    <br>
                </form>


            </div>

            <div class="row">
                {% for city in city_list %}


                <div class="col-md-4">

                        <a href="/cities/{{ city.pk }}">{{ city.name }}</a><br>

                </div>



                {% endfor %}









    </div>


    </div>










</header>




{% endblock %}

app/templates/state_detail.html
{% extends 'base.html' %}

{% block body %}

{% load static %}

<section class="bg-primary" id="about" style="margin-left:auto;">

    <div class="row" style="margin-left:30px;">

    <h1>  {{state.name}} </h1>
        <br>

    </div>

   <div class="row" style="margin-left:30px;" >
       <h3> Includes the following cities:</h3>
       {% for city in cities %}

       <div class="col-md-4 btn-primary text-center" style="margin:5px; width:300px;" >


               <h7 class="bg-primary" style="text-shadow: 3px 2px gray;"><a  href="cities/{{city.pk}}" id="link-special"> {{city.name}}  </a></h7>


       </div>


       {% endfor %}


   </div>





</section>



{% endblock %}

app/templates/state_list.html
{% extends 'base.html' %}
{% block body %}
{% load static %}





    <header>
        <div class="header-content">
            <div class="header-content-inner"   >
                <h1 id="homeHeading">The big US States ! </h1>
                <hr>

                <p class="test">Find below the list of all States and what does it includes and how you can see all the cities in the state please check and give us your opinion</p>
            </div>
        </div>
    </header>
    <br>



    <section class="no-padding" id="portfolio">
        <div class="container-fluid">
            <div class="row" style="margin-left:80px;">
                {% for state in state_list %}
                <div class="col-lg-4 col-sm-6" style="margin:auto;" >

                    <a href= "/states/{{ state.pk }}" class="portfolio-box">

                        <img src= '{%static "" %}/img/portfolio/thumbnails/{{state.name}}.jpg' style="width:200px; height:120px; align:center;" class="img-responsive" alt="No pic" onerror="this.src='{% static 'img/portfolio/thumbnails/image-not-found.jpg' %}'" >
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    State
                                </div>
                                <div class="project-name">
                                    {{ state.name }}
                                </div>
                            </div>
                        </div>
                    </a>
                    <br>



                </div>


                {% endfor %}
            </div>
        </div>
    </section>


    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="primary">
                    <p>Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x sr-contact"></i>
                    <p>+965-65882259</p>
                </div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x sr-contact"></i>
                    <p><a href="mailto:your-email@your-domain.com">usefz89@gmail.com</a></p>
                </div>
            </div>
        </div>
    </section>





{% endblock %}

app/templates/test.html
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type"
content="text/html; charset=UTF-8" />
<title>Untitled Document</title>
</head>
<body>
<h3 id='list-header-one'>This Is The First
List</h3>
<ul class="list" id="list-one">
<li class="list-item" >Cats</li>
<li class="list-item" >Dogs</li>
</ul>
<h3 id='list-header-two'>This Is The Second
List</h3>
<ul class="list" id="list-two">
<li class="list-item" >Retrievers</li>
<li class="list-item" >German
Shepherds</li>
<li class="list-item" >Bulldogs</li>
<li class="list-item" >Beagles</li>
<li class="list-item" >Poodles</li>
</ul>
<script
src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3
.0.0-alpha1/jquery.js"></script>

<script type="text/javascript">

   $('.list').css('display','none');
   $('h3').on('mouseenter', function(e) {
    $('#'+e.target.id).next().fadeIn();
    $('h3').on('mouseleave', function(e) {
    $('#'+e.target.id).next('.list').fadeOut();
    });
    });

</script>


</body>
</html>

app/templates/user_signup.html
{% extends 'base.html' %}
{% block body %}
{% load crispy_forms_tags %}

<header>

    <div class="header-content">

        <div class="header-content-inner">

            <form action="/user_signup/" method="POST">

                {% csrf_token %}

                {{form|crispy}}
                 <input type="submit", value="SignUp" class="btn btn-primary">



            </form>






        </div>




    </div>




</header>
{% endblock %}